apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-demo
  namespace: dev6 # to deploy all service related to nagp assignment in a seperate namespace
spec:
  selector:
    matchLabels:
      app: harness-demo
  replicas: 4
  minReadySeconds: 45
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: harness-demo
    spec:
      containers:
      - name: harness-demo
        image: sanu07/harness-demo:v1
        imagePullPolicy: IfNotPresent
        env:   # Setting Enviornmental Variables
        - name: custom.config   # Setting Database host address from configMap
          value: dev6-v1
        ports:
        - name: h-port
          containerPort: 8080 #backend service runs on port 9000
        resources: #configure for optimum use of resources
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi
        readinessProbe:
          httpGet:
            path: /healthCheck #readinessProbe will confirm the health of the service before starting accepting any request
            port: h-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /healthCheck #livenessProbe will confirm app is up and running
            port: h-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30 #helps in graceful termination