service:
    name: harness_demo
    identifier: harnessdemo
    serviceDefinition:
        type: Kubernetes
        spec:
            manifests:
                - manifest:
                      identifier: harnessdemo
                      type: K8sManifest
                      spec:
                          store:
                              type: Github
                              spec:
                                  connectorRef: harnessdemogitconnector
                                  gitFetchType: Branch
                                  paths:
                                      - kubernetes/2-harness-demo/harness-demo-deployment.yaml
                                      - kubernetes/2-harness-demo/harness-demo-service.yaml
                                  repoName: demo-poc
                                  branch: main
                              skipResourceVersioning: false
                              enableDeclarativeRollback: false
    gitOpsEnabled: false